#!/bin/bash

TEMP_DIR=/home/pi/code/pi-photobooth/.photos
# SYNC_DIR=/home/pi/code/pi-photobooth/photos

echo "resizing images"
mogrify -resize 968x648 $TEMP_DIR/*.jpg
echo "creating montage"
montage $TEMP_DIR/*.jpg -tile 2x2 -geometry +10+10 $1
echo "removing temp images"
rm $TEMP_DIR/*.jpg
echo "done"
